### PR TITLE
Organize code, add files to package.json

### PR DESCRIPTION
**Pull request by pgilad**

### CODE REVIEW

**Comment by wraithgar** [comment]
+1

**Comment by lukekarrys** [comment]
+1

**Comment by lukekarrys** [comment]
Is this worth publishing or should it just wait until the next release?

**Comment by wraithgar** [comment]
Depends on how soon you think the xhr version bump will be.  If it's not gonna be soon I'd say :shipit: instead of waiting.

**Comment by lukekarrys** [comment]
Published as `v3.0.6`

**Pull request merged**
