### PR TITLE
Fixes #32, update to xhr2 with integration tests

### LINKED ISSUE #32: Upgrade to xhr v2.0
`xhr` is now fully compatible with a subset of `request`. Some bugs were eliminated.
It would also make #21 much easier to implement - just by replacing `xhr` with `request`. And with a minor setup the whole ampersand model would work in node.js

Now the http errors are treated as responses, so it's a change that requires a minor update to logic.
I'm planning to do a PR for that, but it'd be nice to open a conversation on that first.

### PR DESCRIPTION
**Pull request by naugtur**

### CODE REVIEW

**Comment by latentflip** [comment]
Nice one! Thanks @naugtur. So just to be totally clear, the only change here is going to be that instead of the raw XHR object, `resp` will now be the wrapped one by xhr?

If so, I'm +1 on this, it's a cleaner api, we merge this and #24 at least, and make this a 2.0.0

Then we can look at what needs to happen in this modules dependents (model/rest-collection) to release those.

**Comment by naugtur** [comment]
To be precise:
`resp` in this line: https://github.com/AmpersandJS/ampersand-sync/pull/45/files#diff-6c5c6e7b7946defd2d15d103e9a56d31L124
will now be a response object as described in https://github.com/Raynos/xhr#var-req--xhroptions-callback
with a `rawRequest` field being a reference to the XMLHttpRequest object

No other changes visible from the user perspective.

**Comment by latentflip** [comment]
Cool, okay, before we merge this, I think we should look at checking it actually works under node, given that that was the purpose in the first place.

I've opened #46, where I'm switching out xhr for request in node, most of the tests pass but a couple fail. Still looking at why that might be.

**Comment by latentflip** [comment]
It looks like this doesn't happen in request:

* https://github.com/Raynos/xhr/blob/master/index.js#L112-L119 to add the right header if it's json data
* and neither does: https://github.com/Raynos/xhr/blob/master/index.js#L157-L161 as request doesn't support beforeSend

so we just need to add that to ampersand-sync too, though, we could do that after merging this arguably, since adding node support won't be a breaking change

ref: #46

**Comment by naugtur** [comment]
I'm looking into running sync in node in regards to #21 and I have a prototype that I now need to run in node and see how it breaks ;)

**Pull request merged**
