### PR TITLE
update testing framework

### PR DESCRIPTION
**Pull request by wraithgar**
Switch fully to zuul
Add saucelabs config
Use node LTS and npm 2 for building

See discussion that led to this here: AmpersandJS/ampersand-filtered-subcollection#26

### CODE REVIEW

**Comment by naugtur** [comment]
This is very cool. 
I wanted to go ~this way with the tests eventually. 
Some questions:

1. Is it possible to replace phantom with electron? From my recent experience it's so much better at being a browser :)  I
ll check if zuul supports it.
2. Things are timing out, looks like the infrastructure that runs it is not permitting outbound request (which sync tests use)
3. Would you mind if I used your configuration in my other projects?

**Comment by wraithgar** [comment]
I think phantom is fine for local tests.  I don't think it matters as much as the CI tests which are being run against real browsers.

Yeah timing out was a huge travis-ci problem yesterday. Hopefully it's better today. Quite bad timing that travis was having all those problems on the day I decided to tackle this.

This code is, as always, MIT licensed ;)

**Comment by wraithgar** [comment]
Looks like we're relying on `mocky.io` for these tests and that's what's timing out, but only from saucelabs.

**Comment by wraithgar** [comment]
Gonna get the other tests working first then come back and refactor the integration tests to run something like sinonjs.

**Comment by naugtur** [comment]
I made these tests send real requests so that they'd cover XDomain issues in older browsers too.
They used to stub the whole `xhr` module and they failed to notice change in it. That's why the rewrite happened.

As long as you stub the XMLHttpRequest, it should be fine. Pro tip: `xhr` provides a way to inject the stub (because it caches a reference to XMLHttpRequest internally and you'd have to require it after stubbing, which would suck)

Not a lot of free time recently, but I could help if you're not in a rush.

**Comment by wraithgar** [comment]
Yeah as far as I can tell that's exactly what sinonjs does (stub the xmlhttprequest).  Gonna try to get it working this afternoon, thanks for the heads up on xhr.

**Comment by naugtur** [comment]
I've been using sinon quite a while and that's what I've been implying here :)

It's a bit tricky, because at first everyone tends to try using the stub handle while it's the global XMLHttpRequest that is replaced.

This should work:
```
var xhr = require("xhr")
var stubHandle = sinon.useFakeXMLHttpRequest()
xhr.XMLHttpRequest = XMLHttpRequest; //becasue it had the original one
```

**Comment by wraithgar** [comment]
Wow you're a saint, thank you so much for solving the problem already.  I'm doing this one last, will start on it after I get the tests in ampersand-view working.

^5

**Comment by wraithgar** [comment]
What a nightmare. Turns out zuul uses xhr and also makes xmlhttprequests during the test suite. Spent all day tracking that little quirk down.

These tests will not work anymore under node, as xhr returns the request library under those circumstances.

**Comment by naugtur** [comment]
Ouch. Looks like you had fun debugging.

I'm on my phone and I only had a moment to look at the code, but I don't see why not just go with jquery.noconflict algorithm here.
```
var xhr = require("xhr")
var stubHandle = sinon.useFakeXMLHttpRequest()
var a=xhr.XMLHttpRequest
xhr.XMLHttpRequest = XMLHttpRequest
XMLHttpRequest=a;
```

**Comment by naugtur** [comment]
I was thinking about it in the background today and I have an idea for a tool that'd solve this without regressing on node tests.

**Comment by wraithgar** [comment]
The noconflict approach wouldn't make any difference cause zuul is requiring xhr too, haha.

**Comment by wraithgar** [comment]
I think this one's ready to go @AmpersandJS/core-team it still maintains IE9+ support.

**Comment by lukekarrys** [comment]
+1

**Comment by wraithgar** [comment]
@naugtur would you be cool w/ merging this till you can make your ideas into another PR?

**Comment by naugtur** [comment]
Sure. It doesn't affect functionality and tests on browsers are a priority.
+1

Also, thanks for asking. :)

**Pull request merged**
